[package]
name = "hex-logic"
version = "0.0.0"
edition = "2021"
authors = ["Carter David Henning"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
